### PR TITLE
Origin/static faq

### PR DESCRIPTION
**Pull request by sachinmilli**

### CODE REVIEW

**Review by carterturn — CHANGES_REQUESTED** [review]
The root.css stylesheet link should be removed from this file (it will be added by the template). Everything else looks good.

**Comment by sachinmilli** [comment]
Removed the root.css stylesheet link

**Review by carterturn — APPROVED** [review]
This looks good!

**Comment by carterturn** [comment]
The timeline of this seems not what I had thought. I apologize if my review was incorrect (I probably should not be doing code reviews that late at night).

**Pull request merged**
